select PTCL_NAME, PTCL_PHASE,PTCL_STAT_CD,PGM_APPLN_ID,X_LEG_INDICATION,X_LEG_THERA_AREA,X_VERIFIED_FLG
from siebel.S_CL_PTCL_LS
where X_VERIFIED_FLG = 'Y'

select PTCL.ROW_ID,PTCL_NAME, PTCL_PHASE,PTCL_STAT_CD,PGM_APPLN_ID,PGMAPP.APPL_NUM,PGMAPP.INDICATOR_CD,PGMAPP.PRODUCT_ID,PROD.NAME,
X_BUSINESS_TYPE,X_GENDER,X_LEG_INDICATION,X_THERA_AREA,X_LEG_THERA_AREA,X_VERIFIED_FLG,
PGM.NAME, ACCNT.NAME
from siebel.S_CL_PTCL_LS PTCL, siebel.S_CL_PGM_LS PGM,siebel.S_CL_PGM_APP_LS PGMAPP, SIEBEL.S_ORG_EXT ACCNT,siebel.S_PROD_INT PROD
where X_VERIFIED_FLG = 'Y' AND PTCL.CL_PGM_ID = PGM.ROW_ID AND PTCL.PGM_APPLN_ID = PGMAPP.ROW_ID AND PTCL.PRDINT_ID = PROD.ROW_ID
AND PGM.X_SPONSOR_ID = ACCNT.ROW_ID
ORDER BY PGM_APPLN_ID 


select * from SIEBEL.S_PTCL_SITE_LS

select * from SIEBEL.S_CL_SUBJ_LS

select * from siebel.S_CL_SUBJ_ST_LS

SELECT PTCL.ROW_ID, PTCL.PTCL_NAME, PTCL.PTCL_NUM,SITE.SITE_NUM,SITE.STATUS_CD,
SUBJ.ROW_ID,SUBJ.SUBJ_NUM,SUBJ.BIRTH_DT, to_char(SUBJ.BIRTH_DT,'YYYYMMDD'),  SUBJ.PTCL_SITE_ID,SUBJ.CREATED,to_char(SUBJ.CREATED,'YYYYMMDD'), 
SJ_STAT.STATUS_CD,SJ_STAT.PAR_SUBJ_ID,to_char(SJ_STAT.STATUS_DATE,'YYYYMMDD'),to_char(SJ_STAT.CREATED,'YYYYMMDD'),SJ_STAT.DB_LAST_UPD_SRC
FROM SIEBEL.S_CL_PTCL_LS PTCL,
SIEBEL.S_PTCL_SITE_LS SITE,
SIEBEL.S_CL_SUBJ_LS SUBJ,
SIEBEL.S_CL_SUBJ_ST_LS SJ_STAT
WHERE SITE.CL_PTCL_ID(+) = PTCL.ROW_ID
AND SUBJ.PTCL_SITE_ID(+) = SITE.ROW_ID
AND SJ_STAT.PAR_SUBJ_ID(+) = SUBJ.ROW_ID
